language: go

go:
  - 1.7
  - 1.8
  - tip

sudo: required

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq nvm
  - sudo nvm install 7.7.4
  - sudo pip install -U pip wheel
  - sudo pip install azure-cli
  - sudo pip install awscli
  - sudo npm install --no-optional -g azure-cli
  - go install github.com/NeowayLabs/nash

script:
  - travis_wait 60 make test logger=stdout
