language: go

go:
  - 1.7
  - 1.8
  - tip

before_install:
  - nvm install 7.7.4

install:
  - pip install -U pip wheel
  - pip install azure-cli
  - pip install awscli
  - npm install --no-optional -g azure-cli
  - go install github.com/NeowayLabs/nash

script:
  - travis_wait 60 make test logger=stdout
