language: go

go:
  - 1.7
  - 1.8
  - tip

sudo: required

before_install:
  - nvm install 7.7.4

install:
  - sudo pip install -U pip wheel
  - sudo pip install azure-cli
  - sudo pip install awscli
  - sudo npm install --no-optional -g azure-cli
  - go install github.com/NeowayLabs/nash

script:
  - travis_wait 60 make test logger=stdout
