dist: trusty

sudo: required

before_script:
  - travis_wait 130 make image

# right now the tests are not as resilient as a CI needs =(
# damn azure
script:
  - make image
# - travis_wait 130 make test-integration logger=stdout
